### ISSUE TITLE
Melhorar pagina de registro de entidades 

### ISSUE THREAD

**Issue by marceldfs** [marceldfs/Agribusiness#11]
Deves melhorar a pagina criada no issue #7 , tem dependencia do issue #7

**Comment by marceldfs** [comment]
Diogo comeca a trabalhar nesta tarefa assim que poderes

**Comment by marceldfs** [comment]
O register.zul nao deve estar dentro do index.zul

**Comment by diiogo91** [comment]
Efectuei o melhoramento da página de registro.
