### ISSUE TITLE
Recriar index.zul

### ISSUE THREAD

**Issue by marceldfs** [marceldfs/Agribusiness#14]
Diogo deves recriar o index.zul.

Basea-te no mookup Homepage.png que esta no repositorio.
NOTA: o home.zul deve ser chamado para o index.zul atraves de um include.
Para mais detalhes contacta-me.

NOTA2: Faca algo simples, facil de manter e bonito.

**Comment by diiogo91** [comment]
Marcel , peço para disponibilizares o  Homepage.png em anexo para eu poder prosseguir com a task.

**Comment by marceldfs** [comment]
https://github.com/marceldfs/Agribusiness/tree/master/Mookups

**Comment by marceldfs** [comment]
O Homepage.png sempre esteve no repositorio
