### ISSUE TITLE
Linkar janelas ao index.zul

### ISSUE THREAD

**Issue by marceldfs** [marceldfs/Agribusiness#16]
Deves linkar a janela de autenticação ao index.zul
E a janela de autenticação a Janela de registro

**Comment by marceldfs** [comment]
Diogo comeca a trabalhar nisto ASAP

**Comment by marceldfs** [comment]
Adiciona dois botoes registar e autenticar e linka as paginas

**Comment by diiogo91** [comment]
Adicionei os botoes registrar e autenticar ao menu e linkei as suas respectivas páginas onde o registrar abre numa nova página e autenticar abre no index.zul
