### ISSUE TITLE
Adicionar menu admin ao menu do index.zul

### ISSUE THREAD

**Issue by marceldfs** [marceldfs/Agribusiness#18]
Por agora so isto ainda vou dar mais detalhes

**Comment by diiogo91** [comment]
Adicionei o Menu Admin e Coloquei como Opções Grupos, Permissões e Utilizadores.

**Comment by diiogo91** [comment]
![untitled](https://cloud.githubusercontent.com/assets/6979932/8037557/a5f38ae8-0dfe-11e5-932e-287ed4582622.png)

**Comment by marceldfs** [comment]
Fechada
