### ISSUE TITLE
Criar tabelas

### ISSUE THREAD

**Issue by marceldfs** [marceldfs/Agribusiness#3]
Tassio, deves criar as tabelas descritas no Diagrama_Classe que se encontra na pasta Diagramas.
Cria em Mysql 5.5 e deves fazer commit de um dump da bd contendo a estrutura e coloca a versao no nome do dump (0.1)

**Comment by TRosario619** [comment]
criacao *

**Comment by marceldfs** [comment]
Os nomes dos atributos nao estao em concordancia com a documentacao.

**Comment by marceldfs** [comment]
Corrige os nomes dos atributos

**Comment by marceldfs** [comment]
Fechada
