### ISSUE TITLE
Criar script de importacacao de dados de regioes

### ISSUE THREAD

**Issue by marceldfs** [marceldfs/Agribusiness#4]
Tassio deves criar um script que vai importar dados em csv para as tabeals provincia, distrito e localidade. E deves depois comitar esse script.

**Comment by marceldfs** [comment]
Tassio fechar isto de uma vez por todas faz favor, colocar me esses exemplos

**Comment by TRosario619** [comment]
ok... tratando ja

2015-05-24 20:16 GMT+02:00 marceldfs notifications@github.com:

> Tassio fechar isto de uma vez por todas faz favor, colocar me esses
> exemplos
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/marceldfs/Agribusiness/issues/4#issuecomment-105045703
> .

## 

_Tássio Freitas Guimarães do Rosário_
Estudante do 4° Ano de Engenharia Informática e Telecomunicações no
_INSTITUTO SUPERIOR DE TRANSPORTE E COMUNICAÇÕES - ISUTC_
Mobile: +258848612581 +258826536751
