### ISSUE TITLE
Criar pagina home.zul 

### ISSUE THREAD

**Issue by marceldfs** [marceldfs/Agribusiness#5]
A pagina home.zul deve ter uma mensagem de boavindas.
O ponto mais crucial da janela home.zul deve ser a existencia de um slideshow de jquery.
Tens um exemplo basico do slideshow:
http://www.jssor.com/demos/image-slider.html

Nota: atraves de certas funcionalidades devera ser possivel alterar as imagens que passam pelo slideshow, mas para efeitos desta tarefa podes colocar algumas estaticas relacionadas com o agribusiness.

**Comment by marceldfs** [comment]
Deadline e 4f da proxima semana dia 29, anything tell me in advance.

**Comment by diiogo91** [comment]
OK. Vou começar a trabalhar nisto.

**Comment by marceldfs** [comment]
Diogo, quando terminas uma tarefa deves fechar o issue aqui. Depois pergunta, na tarefa falava-se de criar home.zul, nao vi nenhum home.zul, mas vi um index.zul com algo parecido com o que devia estar no home.zul podes explicar me o que aconteceu ?

**Comment by diiogo91** [comment]
Foi um engano meu Marcel , desculpa , vou ja retificar

**Comment by marceldfs** [comment]
Fechada
